### ISSUE TITLE
Incompatibility with rehype-slug+rehype-autolink-headings

### ISSUE THREAD

**Issue by MoOx** [wooorm/rehype-raw#7]
I am trying to allow a permissive parsing to get a flexible mardown to react rendering with mapping.
I saw [in a comment](https://github.com/mapbox/remark-react/issues/45#issuecomment-308823987) that using rehype-raw was one solution. And it looks good!

I just found an issue tho.
Whenever I use remark/rehype -slug+autolinks (I tried with remark-* initially and when I got the issue, tried with rehype-* versions but no luck) with rehype-raw, I am getting an error.

Here is a minimal snippet that should trigger a similar error I am getting

```js
var unified = require('unified');
var markdown = require('remark-parse');
var remark2rehype = require('remark-rehype');
var slug = require('rehype-slug');
var link = require('rehype-autolink-headings');
var raw = require('rehype-raw');
var stringify = require('rehype-stringify');

const input = `## Test
[link](href)
\`\`\`js
console.log(window)
\`\`\`

<button>Random Html</button>
<Button>Random react like stuff</Button>
`;

unified()
  .use(markdown)
  .use(remark2rehype, {allowDangerousHTML: true})
  .use(slug)
  .use(link)
  .use(raw)
  .use(stringify)
  .processSync(input);
```

You can test is there http://requirebin.com/?gist=3feede6e8cc19e061589bdc2f6634bef

And here is my version of the error

```
TypeError: Cannot read property 'length' of undefined
      
      at all (node_modules/hast-util-raw/index.js:103:23)
      at element (node_modules/hast-util-raw/index.js:120:5)
      at one (node_modules/zwitch/index.js:20:25)
      at all (node_modules/hast-util-raw/index.js:107:7)
      at element (node_modules/hast-util-raw/index.js:120:5)
      at one (node_modules/zwitch/index.js:20:25)
      at all (node_modules/hast-util-raw/index.js:107:7)
      at element (node_modules/hast-util-raw/index.js:120:5)
      at one (node_modules/zwitch/index.js:20:25)
      at all (node_modules/hast-util-raw/index.js:107:7)
      at root (node_modules/hast-util-raw/index.js:112:5)
      at one (node_modules/zwitch/index.js:20:25)
      at fragment (node_modules/hast-util-raw/index.js:85:5)
      at wrap (node_modules/hast-util-raw/index.js:41:43)
      at wrapped (node_modules/trough/index.js:93:19)
      at next (node_modules/trough/index.js:56:24)
      ...
```

Not sure if it's directly a rehype-raw error but I don't have it until I use this module, that's why I opened an issue here :)

**Comment by MoOx** [comment]
Sorry to be annoying @wooorm, but do you have any clue about where should I look to fix this bug?

**Comment by wooorm** [comment]
Sorry for the slow reply! I’m super busy making a syllabus for a class that’s starting soon.

This seems to work, any reason why you’re not using it?

```diff
var unified = require('unified');
var markdown = require('remark-parse');
var remark2rehype = require('remark-rehype');
var slug = require('rehype-slug');
var link = require('rehype-autolink-headings');
var raw = require('rehype-raw');
var stringify = require('rehype-stringify');

const input = `## Test
[link](href)
\`\`\`js
console.log(window)
\`\`\`

<button>Random Html</button>
<Button>Random react like stuff</Button>
`;

unified()
  .use(markdown)
  .use(remark2rehype, {allowDangerousHTML: true})
+ .use(raw)
  .use(slug)
  .use(link)
- .use(raw)
  .use(stringify)
  .processSync(input);
```

**Comment by wooorm** [comment]
The problem has two sides btw:

* [`rehype-autolink-headings`](https://github.com/wooorm/rehype-autolink-headings/blob/5dcadd5de723b039ede43d883cf2f85ec86bb746/index.js#L12-L16) creates invalid elements (those without `children`)
* [`hast-util-raw`](https://github.com/syntax-tree/hast-util-raw/blob/master/index.js#L103) cannot deal with invalid elements (those without `children`)

**Comment by MoOx** [comment]
Yeah I saw that with your github activity. Hope I didn't bother you too much!
For your response... Wow, that's weird (UX speaking). Anyway, it's working indeed. Feel free to close if you feel this issue is not relevant then.

My knowledge of unified and friends is limited (I am kind of "mind blow" of the work you did to be honest).

Thanks for you previous time!

**Comment by MoOx** [comment]
Oh I see. Glad you find the origins of the problem. Should I open issues over there?

**Comment by wooorm** [comment]
> Yeah I saw that with your github activity. Hope I didn't bother you too much!
> For your response... Wow, that's weird (UX speaking). Anyway, it's working indeed. Feel free to close if you feel this issue is not relevant then.

...and...

> Oh I see. Glad you find the origins of the problem. Should I open issues over there?

No problem, I’ll fix them there and close this issue when done! I’d like to create more starter issues, but as you’ve been waiting for a week and I don’t have a lot of time mentoring people into the ecosystem right now I’ll just do it myself now.

> My knowledge of unified and friends is limited (I am kind of "mind blow" of the work you did to be honest).

Thank you! I like the code and where it’s going, but there’s a lot of stuff and thoughts that are only in my head and not in docs. If you have suggestions for documentation, please let me know by creating an issue, pinging me, or chatting in Gitter. I’d love to get better docs!
